# Default values for stressforge.
# This is a YAML-formatted file.

image:
  registry: atharva608
  tags:
    api: "28"
    frontend: "28"
    worker: "28"
    locust: "28"
# Future configurations (secrets, replicas, etc.) could be added here
