# Default values for stressforge.
# This is a YAML-formatted file.

image:
  registry: atharva608
  tags:
    api: "23"
    frontend: "23"
    worker: "23"
    locust: "23"
# Future configurations (secrets, replicas, etc.) could be added here
