# Default values for stressforge.
# This is a YAML-formatted file.

image:
  registry: atharvapudale
  tags:
    api: "23" # Jenkins will update these tags
    frontend: "23"
    worker: "23"
    locust: "23"
# Future configurations (secrets, replicas, etc.) could be added here
